### ISSUE TITLE
Custom time

### ISSUE THREAD

**Issue by Martin-Pitt** [franciscop/ola#3]
Since Ola actually uses maths, it currently only uses the existing time.
A user might like to predict or look ahead for future positions (& speeds).

For example if I had a boid/particle swarm and wanted to debug/visualise a future trajectory, I'd draw a line or points.

Another usecase might be multiplayer games, where servers & clients may need to predict future values.

Are there other usecases?

Does Ola need to change to support usecases like that in some way?

This is just a rough idea. I'm not sure there is a strong case for it, doesn't seem like a big deal to add it either, apart from API complexity and documentation.

**Comment by franciscop** [comment]
I did think about adding support for this in the getter like:

```js
const pos = Ola({ x: 0,  y: 0});
pos.set({ x: 100, y: 100 });
console.log(pos.get('x'));  // Now, shows 0
console.log(pos.get('x', 300));  // In 300ms, shows. "100"
```

But I'm not sure how useful this usecase might be. My main concern *not* to do this is that it's not keeping track of the past/future events, so it would be trickier if only some slice of time is supported but not others:

```js
pos.get('x'); // Default
pos.get('x', 0);  // Does that mean now? Or creation time?
pos.get('x', 100); // Okay, in 100ms sure
pos.get('x', new Date() + 100);   // Wait when?
pos.get('x', -100);  // Cannot? Maybe?
pos.get('x', new Date() -100);
```

I feel the potential for confussion is too big here. So I'd rather keep this out.

> Another usecase might be multiplayer games, where servers & clients may need to predict future values.

For multiplayer games you normally need to predict the *current* time right? Like, "the last order received was to move to X, so now it's moving there". If you do need to keep a "moving to", you could keep that as a variable:

```js
const pos = Ola({ x: 0, y: 0 });
let target = { x: 0, y: 0 };
socket.on('move', e => {
  pos.set(e.data);
  target = e.data;
});

// Able to read both pos.x (current position) and target.x (target position)
```

I don't think this will be implemented, but if you can bring a strong argument it might :)

**Comment by franciscop** [comment]
Okay added this feature internally on the `1.1.0` besides another feature that fixes array looping, unfortunately reading different times *does* have inconsistencies as predicted (see testing). So this is not officially supported, but the code works :)
