### ISSUE TITLE
When should i clear the interval?

### ISSUE THREAD

**Issue by chenquincy** [franciscop/ola#6]
The demo use `setInterval` to update another value, any prop of Ola instance can let me know the update is over?
Such as a Boolean `__done__` prop:
``` javascript
const data = new Ola({x: 0});
data.set({x: 10});

let target;
let intervalId;
intervalId = setInterval(() => {
  target = data
  if (data.__done__) {
    clearInterval(intervalId)
  }
}, 10)
```

**Comment by franciscop** [comment]
Oops sorry I forgot to reply to this! 

You can see the more advanced config in here:
https://github.com/franciscop/ola#advanced-usage

There are multiple ways this can be achieved, the most straightforward one I can think of is using `data.$x`, which is the value that is going to be updated to after the internal interval passes, [see this JSFiddle](https://jsfiddle.net/franciscop/gmyshtfj/):

```js
const data = new Ola({x: 0});
data.set({x: 10});

let target;
let intervalId;
intervalId = setInterval(() => {
  target = data
  console.log(data.x, data.$x)
  if (data.x === data.$x) {
    console.log('Cleared!')
    clearInterval(intervalId)
  }
}, 50);
```

Output:

```
0.8260532972577543 10
3.0474136084113255 10
6.575735053686507 10
8.795097124661508 10
9.997020336103564 10
10 10
Cleared!
```

**Comment by franciscop** [comment]
Please let me know if you have any further questions or this doesn't solve the initial question, happy to reopen!
